// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4TvpmzU6jluLLb6ynJX518ah6P3HL4g0',
    appId: '1:634896081513:web:ac291d5a597d0d467738f8',
    messagingSenderId: '634896081513',
    projectId: 'android-start-7865f',
    authDomain: 'android-start-7865f.firebaseapp.com',
    databaseURL: 'https://android-start-7865f.firebaseio.com',
    storageBucket: 'android-start-7865f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Z_CQqIcG6xAFcdvN3wYlSWrr2isv7T8',
    appId: '1:634896081513:android:0081ffa190aa9c467738f8',
    messagingSenderId: '634896081513',
    projectId: 'android-start-7865f',
    databaseURL: 'https://android-start-7865f.firebaseio.com',
    storageBucket: 'android-start-7865f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKCYhlIER8Zu-9zfGFgSojR9Nkiv7kww',
    appId: '1:634896081513:ios:0c55a3e81aa443b87738f8',
    messagingSenderId: '634896081513',
    projectId: 'android-start-7865f',
    databaseURL: 'https://android-start-7865f.firebaseio.com',
    storageBucket: 'android-start-7865f.appspot.com',
    androidClientId: '634896081513-h2je21nn81bik5cln18jm4rrav561837.apps.googleusercontent.com',
    iosClientId: '634896081513-n6ushchaq78hvcr8qge8a52633ppl4gc.apps.googleusercontent.com',
    iosBundleId: 'io.jvcss.smartFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQKCYhlIER8Zu-9zfGFgSojR9Nkiv7kww',
    appId: '1:634896081513:ios:bfb839beec253ce37738f8',
    messagingSenderId: '634896081513',
    projectId: 'android-start-7865f',
    databaseURL: 'https://android-start-7865f.firebaseio.com',
    storageBucket: 'android-start-7865f.appspot.com',
    androidClientId: '634896081513-h2je21nn81bik5cln18jm4rrav561837.apps.googleusercontent.com',
    iosClientId: '634896081513-jd6upk2tagi48trt8li7b442qkse0qit.apps.googleusercontent.com',
    iosBundleId: 'io.jvcss.smartFood.RunnerTests',
  );
}
